import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
// ThemeProvider will be managed by useAppData and applied in page.tsx or a client wrapper there
// For now, layout.tsx remains simpler. Theme is applied to <html> via ThemeProvider's useEffect.

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'ZipGroup', // Default title, will be overridden by pageTitle
  description: 'Organize and share groups of links with ZipGroup.link.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* The favicon link will be automatically generated by Next.js
            if you place 'icon.png' (or 'favicon.ico') in the 'src/app/' directory.
            User has 'favicon.png', which should be moved to 'src/app/icon.png'.
        */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ThemeProvider will wrap content in page.tsx or a client component there */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
